---
- name: Install UFW on Ubuntu
  ansible.builtin.apt:
    name: ufw
    state: present
  when:
    - ansible_os_family == 'Debian'
    - enable_firewall | bool

- name: Set UFW default deny
  community.general.ufw:
    direction: incoming
    policy: deny
  when:
    - ansible_os_family == 'Debian'
    - enable_firewall | bool

- name: Allow required TCP ports on Ubuntu
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ allowed_tcp_ports | default([22]) }}"
  when:
    - ansible_os_family == 'Debian'
    - enable_firewall | bool

- name: Enable UFW
  community.general.ufw:
    state: enabled
  when:
    - ansible_os_family == 'Debian'
    - enable_firewall | bool

- name: Install firewalld on RHEL
  ansible.builtin.dnf:
    name: firewalld
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - enable_firewall | bool

- name: Enable firewalld on RHEL
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started
  when:
    - ansible_os_family == 'RedHat'
    - enable_firewall | bool

- name: Allow required TCP ports on RHEL
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ allowed_tcp_ports | default([22]) }}"
  when:
    - ansible_os_family == 'RedHat'
    - enable_firewall | bool
